In [2]:
import numpy as np

# Given 1D data
data = [1, 3, 7, 15, 31, 63, 127, 255]

# Define the sequence length (number of time steps to consider for each sample)
sequence_length = 5

# Prepare input sequences and corresponding target values
input_sequences = []
target_values = []

for i in range(len(data) - sequence_length):
    input_seq = data[i:i + sequence_length]
    target_value = data[i + sequence_length]
    input_sequences.append(input_seq)
    target_values.append(target_value)

# Convert lists to numpy arrays
X = np.array(input_sequences)
y = np.array(target_values)

print("Input data (2D array):")
print(X)
print("Corresponding target values:")
print(y)


Input data (2D array):
[[  1   3   7  15  31]
 [  3   7  15  31  63]
 [  7  15  31  63 127]]
Corresponding target values:
[ 63 127 255]
